package com.alibaba.cardscanner.infrastructure.mapper;

import com.alibaba.cardscanner.infrastructure.model.UserCard;
import com.alibaba.cardscanner.infrastructure.model.UserCardExample;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Created by rmy on 16/6/25.
 */
public interface UserCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int countByExample(UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int deleteByExample(UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    Long insert(UserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int insertSelective(UserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    List<UserCard> selectByExample(UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    UserCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserCard record, @Param("example") UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int updateByExample(@Param("record") UserCard record, @Param("example") UserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int updateByPrimaryKeySelective(UserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card
     *
     * @mbggenerated Sun Jun 26 16:04:22 CST 2016
     */
    int updateByPrimaryKey(UserCard record);
}